### ISSUE TITLE
A question about descruction

### ISSUE THREAD

**Issue by ptelad** [jeffijoe/libx#11]
Hi,
Great lib so far!
I've read the README through and through and did not find anything about removing references.

Let say I have model A that created a model B and is referencing it in a computed property.
If A is removed, I want to make sure B is removed as well.

Is it possible? What did I miss?

**Comment by jeffijoe** [comment]
If you use a computed like

```ts
@computed
get author() {
  return this.rootStore.authorStore.authors.get(this.authorId)
}
```

Then if the corresponding author is removed from the store, the computed will point to `undefined`. Whether or not this is what you want is up to you. I've done both styles where the removal from a collection does not mean invalidation of references.
