### ISSUE TITLE
Add LoDash orderBy method to collection

### ISSUE THREAD

**Issue by francesco-carrella** [jeffijoe/libx#2]
It's a really great idea to add LoDash method to the libx collection!

I think that a sorting method also should be a 'must' when we are talking about collections. LoDash has at least 2 methods to do that: sortBy & orderBy, where orderBy is more complete because he allows to specify the sorting order. 

Do you see some complexity to use LoDash orderBy method?

https://lodash.com/docs/4.17.4#orderBy

**Comment by jeffijoe** [comment]
Not at all, the most complex part is adding the TS definitions.

**Comment by jeffijoe** [comment]
Implemented and published as 0.1.6 :shipit:

**Comment by francesco-carrella** [comment]
Many thanks @jeffijoe, I really appreciate your efforts

**Comment by jeffijoe** [comment]
Thanks for trying out LibX 🙇
