### ISSUE TITLE
Cross-store communication and reactions

### ISSUE THREAD

**Issue by le0nik** [jeffijoe/libx#4]
Hello and thanks for this lib!

I've implemented something similar in my projects before and there is one big problem I've encountered. And it's with cross-store communication and setting up reactions in store's `constructor` methods.

Say you have 2 stores: `A` and `B` and inside your `RootStore` you create `A` store first. Now you get the reference to the instance of `RootStore` inside `A`'s constructor, but you don't have a reference to the `B` store because at that point it doesn't exist yet.

How do you set up mobx `reaction`s in `A` store that would depend on observables from store `B`?

I've ended up splitting creation and initialization of stores into 2 phases: `constructor` and `init`(meaning that first all stores are created and then all `init` methods are called on those stores) so inside `init` method of any store you have access to any other store and by convention we only set up reactions and otherwise reference other stores only inside those `init` methods.

How do you solve this problem in this library?

**Comment by jeffijoe** [comment]
Hi there, thank you!

That is a good question! This is a common problem when using dependency injection – circular dependencies. Preferably they should be avoided, but in UI code that can be quite hard, so I would suggest you do the following:

In your stores, you could define an optional `initialize () {}` method. In your root store, after constructing all the stores, call their `initialize` function.

```js
class AStore extends Store {
  initialize (opts) {
    const rootStore = opts.rootStore // or use `this.rootStore`, it has all stores at this point
    reaction(() => rootStore.bStore.someObservable, () => ...)
  }
}

class BStore extends Store {

}

class RootStore {
  constructor () {
    this.aStore = new AStore({ rootStore: this })
    this.bStore = new BStore({ rootStore: this })
    // All stores have been added, call initialize on all of them if present.
    for (const prop in this) {
      const val = this[prop]
      if (val.initialize) {
        val.initialize({ rootStore })
      }
    }
  }
}
```

Does that answer your question? 😃

**Comment by le0nik** [comment]
Yes, thank you! Yes that's the best way I found too.
